# Pipeline for dev branch current project
trigger:
  branches:
    include:
    - dev/*
    exclude:
    - release/*
    - master
pr:
  branches:
    include:
    - dev/*

resources:
  repositories:
    - repository: global_pipeline_template
      name: GetcuReone-Pipelines
      type: git

variables:
- group: global-variables-group
- group: GetcuReone-MvvmFrame-variables-group
- name: 'buildConfiguration'
  value: 'debug'
- name: 'patchVersion'
  value: $[counter(format('{0}.{1}', variables.majorVersion, variables.minorVersion), 0)]

name: $(Build.DefinitionName)-$(majorVersion).$(minorVersion).$(patchVersion)

jobs:
  - template: nuget/dev_nuget_build_template.yml@global_pipeline_template
