# Pipeline for master branch current project
trigger:
  branches:
    include:
    - master
    exclude:
    - release/*
    - dev/*
pr:
  branches:
    include:
    - master

resources:
  repositories:
    - repository: global_pipeline_template
      name: GetcuReone-Pipelines
      type: git

variables:
- group: global-variables-group
- group: GetcuReone-MvvmFrame-variables-group
- name: 'buildConfiguration'
  value: 'release'
- name: 'patchVersion'
  value: $[counter(format('{0}.{1}', variables.majorVersion, variables.minorVersion), 0)]
- ${{ if eq(variables['Build.SourceBranchName'], 'master') }}:
  - name: 'buildName'
    value: $[format('{0}-{1}.{2}.{3}', variables['Build.DefinitionName'], variables['majorVersion'], variables['minorVersion'], variables['patchVersion'])]
- ${{ if not(eq(variables['Build.SourceBranchName'], 'master')) }}:
  - name: 'buildName'
    value: $[format('{0}-{1}.{2}.{3}-pullRequest', variables['Build.DefinitionName'], variables['majorVersion'], variables['minorVersion'], variables['patchVersion'])]

name: $[variables.buildName]

jobs:
  - template: nuget/master_nuget_build_template.yml@global_pipeline_template
